# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8d4cd00f8b974663430cd984bbef1923eb992ac0eb9314fc98ef26f38f9b159b861564060cd8a4378271b881900efea4527bdb4e1da53bce5ec6bec6494a930

test:
  secret_key_base: 088586eaeb1a334482fad18a1f8b2c85d062848b76c6236dfd6a9ea4211a8471b43c55897baadf6cd0a96ad1660a38decdf19fc40fce349067541375c4305880

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
